### ISSUE TITLE
need help for m3u8_video_crawler

### ISSUE THREAD

**Issue by asdasdqqq** [youyouzh/PythonPractice#1]
recently the miss site update its rules.
when I download m3u8 url in miss，it return the logs :
[u_file.py:175]	 The response status is invalid. code: 403, content: xxxxx

**Comment by youyouzh** [comment]
maybe you need modify the Refer header like:  `Referer': 'https://missav.com/'`
please check the value of `_REQUESTS_KWARGS.headers.Referer`.

**Comment by youyouzh** [comment]
> recently the miss site update its rules. when I download m3u8 url in miss，it return the logs : [u_file.py:175] The response status is invalid. code: 403, content: xxxxx

maybe you need modify the Refer header like: `Referer': 'https://missav.com/'`
please check the value of `_REQUESTS_KWARGS.headers.Referer`.

**Comment by asdasdqqq** [comment]
-        # 'Referer': 'https://missav.com',
-        'Referer': 'https://javplayer.me/',
+        'Referer': 'https://missav.com/dm13/cn/gana-2883',
+        # 'Referer': 'https://javplayer.me/',
-# ('xxx', 'https://ap-drop-monst.mushroomtrack.com/bcdn_token=xxx&token_path=11012.m3u8'),
+ ('GANA-2883', 'https://surrit.com/143e1e24-7c93-4924-8b7f-ea378bb9c551/640x360/video.m3u8'),

no more chages, the same error,[u_file.py:175]	 The response status is invalid. code: 403, content: xxx

**Comment by youyouzh** [comment]
> recently the miss site update its rules. when I download m3u8 url in miss，it return the logs : [u_file.py:175] The response status is invalid. code: 403, content: xxxxx

I test it，the site actually update it's rules,  it add the Origin header check. I have fixed it . you can `git fetch` the new code ,
or add the header:  `'Origin': 'https://missav.com'`.

**Comment by youyouzh** [comment]
And you can try my another open source chrome extension tool:   `chrome_tools`, it can automatically extract the m3u8 video links and the video title  from web pages.
Good Luck Boy~

**Comment by asdasdqqq** [comment]
I  add the header: `'Origin': 'https://missav.com'` and the problem was solved. Thanks a lot and the recommendation！
